### ISSUE TITLE
It's not working with ST 4070+

### ISSUE THREAD

**Issue by ihodev** [sublimelsp/LSP-angular#1]
Details: 

https://github.com/sublimehq/sublime_text/issues/3545

**Comment by rchl** [comment]
It's strange... That bug should not cause the server to not work. I've only seen it happen in tests where sessions are started and stopped very fast.

I would think that if you are getting this issue, the issue would be that the server is crashing on start immediately (due to unrelated issue).

**Comment by ihodev** [comment]
I'm investigating it, but it works in ST3 for sure.

**Comment by ihodev** [comment]
I believe that something is wrong on `@angular/language-server` side (when I enable ls logging, plugin works in ST 4070+), will do further investigation.

TODO: Check this [issue](https://github.com/angular/vscode-ng-language-service/issues/876)

**Comment by rchl** [comment]
Wasn't easy but found the issue: https://github.com/sublimelsp/LSP/pull/1238
So it's an LSP bug after all.

**Comment by ihodev** [comment]
That's cool! Thanks!
