### ISSUE TITLE
Use TSC_NONPOLLING_WATCHER

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-angular#2]
```
LSP-angular: Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.
```

You can set env variables through `env` key.
It seems like VSCode extension does set it also.

**Comment by ihodev** [comment]
I tried before:

```json
"env": {
    "TSC_NONPOLLING_WATCHER" : "true"
}
```

but that message continued to appear, will check again tomorrow, thanks!

**Comment by rchl** [comment]
It worked for me as a root key in `LSP-angular.sublime-settings`.
