### ISSUE TITLE
The HTML language ID

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-angular#4]
I see that the [languageId is set to html](https://github.com/sublimelsp/LSP-angular/blob/095b7a1bdba9d39e6d194a6f174f2b7ba153001d/LSP-angular.sublime-settings#L4-L14), but the selector is different from regular html. That is, the selector here is `text.html.ngx` but other server setups use `text.html.basic`. If we want to abstract away these document selectors they should all agree for every VSCode language ID.

Could you try changing the languageId to `html-ngx` and see if this Angular server still works as expected?

**Comment by rwols** [comment]
It's a server that only works for one languageId so I doubt it even looks at the languageId that we send in textDocument/didOpen

**Comment by rchl** [comment]
Just a quick search in the server's code returns this:
https://github.com/angular/vscode-ng-language-service/blob/546870c3a486424200aecd1b8255f68ff1dbb415/server/src/session.ts#L26-L29

So it does support multiple languageId's and we should also add `typescript` here.

**Comment by rchl** [comment]
Looking at the logic where it compares languageId, it seems like it only explicitly checks for `typescript` and if it gets something else, it won't really use that value for anything.

https://github.com/angular/vscode-ng-language-service/blob/546870c3a486424200aecd1b8255f68ff1dbb415/server/src/session.ts#L253

So changing to `html-ngx` should work but I wouldn't personally recommended that as it's not official ID it supports and things could break in the future.

**Comment by rwols** [comment]
I thought `{"languageId": "html", "pattern": "**/*.component.html?"}` would perhaps be necessary, given that [that's the file extension of this HTML Ngx syntax](https://github.com/princemaple/ngx-html-syntax/blob/d5bae234d7a762bd1535128ea950139a65936383/NgxHTML.sublime-syntax#L4-L5). But the VSCode client just starts this server for any html file? I'm not well-versed in typescript though https://github.com/angular/vscode-ng-language-service/blob/546870c3a486424200aecd1b8255f68ff1dbb415/client/src/extension.ts#L28-L33

**Comment by rwols** [comment]
The problem with having different Sublime text selectors for the same language ID is that the matchers are different (obviously), but that causes the language ID stored in the `view.settings()` to be ambiguous and dependent on the particular server config.

**Comment by ihodev** [comment]
> Could you try changing the languageId to html-ngx and see if this Angular server still works as expected?
I'll check on the weekends

> So it does support multiple languageId's and we should also add typescript here.
Initially, I added `typescript`, but from time to time `LSP-angular` was replacing `LSP-typescript` capabilities, I'll check this too.

**Comment by rwols** [comment]
> but from time to time LSP-angular was replacing LSP-typescript capabilities, I'll check this too.

What you can do in that case (provided that theia's typescript-language-server is better than angular's), is you can set an empty feature_selector so that its score is always 1, which is less than 16 (= score of typescript's langserver). This will select the typescript langserver in case there's multiple providers (e.g. for completionProvider).

In code:

```js
{
    "languageId": "typescript",
    "document_selector": "source.ts",
    "feature_selector": ""  // prefer other typescript langservers over this one
}
```

**Comment by ihodev** [comment]
@rwols, hello :)

> I thought {"languageId": "html", "pattern": "**/*.component.html?"} would perhaps be necessary

I did some investigation, and I can say that VSCode client starts this server for any HTML file, but only if a valid `tsconfig.json` file is present in the workspace folder. 

I've changed language id to `html-ngx` and I believe everything is working.

> "feature_selector": ""  // prefer other typescript langservers over this one

It seems that the empty `feature_selector` is not working, because `LSP-angular` still overrides `LSP-typescript` with the next configuration:

```js
{
	"languages": [
		{
			"languageId": "html-ngx",
			// ST3 configuration
			"scopes": [
				"text.html.ngx"
			],
			"syntaxes": [
				"Packages/Ngx HTML/NgxHTML.sublime-syntax"
			],
			// ST4 configuration
			"document_selector": "text.html.ngx",
			"feature_selector": "text.html"
		},
		{
			"languageId": "typescript",
			// ST3 configuration
			"scopes": [
				"source.ts"
			],
			"syntaxes": [
				"Packages/JavaScript/TypeScript.sublime-syntax",
				"Packages/TypeScript Syntax/TypeScript.tmLanguage",
				"Packages/User/JS Custom/Syntaxes/TypeScript.sublime-syntax"
			],
			// ST4 configuration
			"document_selector": "source.ts",
			"feature_selector": ""
		}
	],
	"initializationOptions": {},
	"settings": {},
	"env": {
		"TSC_NONPOLLING_WATCHER": "true"
	}
}
```

**Comment by rwols** [comment]
Hmm, I agree with rchl in that the language ID should stay `html` as things can break in the future. Apologies for not communicating that clearly enough.
