### ISSUE TITLE
Work with local deps

### ISSUE THREAD

**Issue by princemaple** [sublimelsp/LSP-angular#96]
Hi,

Now that angular 16 is released, this package needs some updates... However, users of this package could be very different versions of angular. What's the proper config to make this package use local node_modules? This should probably be in the README.

An easy workaround for the moment, for users of this package, is to extract this package and manually update the `package.json` in `server/` to their angular version and typescript version.

Thanks for this package!

**Comment by predragnikolic** [comment]
Thanks for the issue, 

Here is a couple of suggestion.
a) we want to maintain only the v16 server for the plugin. And leave in the release notes that if you need angular <16, please download the previous release.  It looks like the VS code extension also does it like that.
https://github.com/angular/vscode-ng-language-service#versioning
> The language service extension relies on the @angular/language-service and typescript packages for its backend. @angular/language-service is always bundled with the extension, and is always the latest version at the time of the release. typescript is loaded, in order of priority, from:

but in VS code the users can easily select what version to install from the marketplace. 

b) somehow ship both servers with the server and expose a setting to switch between servers?

c) leave this extension as is, and create a new LSP-anggular-v16 extension? Pretty bad. I will not go with `c`, but I also thought about something like that.

d) some other idea...

----

The easiest option from the maintenance point would be option `a`)

**Comment by princemaple** [comment]
Yeah fine by me. I'm always on the latest version. Just something came through my mind and I was hesitant to send a pr to update this package to angular 16. Hence the issue. 😊
